<?php

/**
 * @file
 * Contains install functions for Helfi Base Config.
 */

/**
 * Implements hook_install().
 *
 * Install HDBT and HDBT admin themes and make them as default themes.
 */
function helfi_grant_applications_config_install() {

  $system_theme = \Drupal::configFactory()->getEditable('system.theme');
  $system_theme->set('default', 'helfi_grants')->set('admin', 'hdbt_admin')->save();

}
